### ISSUE TITLE
Lots of empty commits

### ISSUE THREAD

**Issue by franzs** [daboynb/autojson#2]
This is issue was touched in https://github.com/daboynb/autojson/pull/1 already.

Empty commits are used to trigger the [workflow](https://github.com/daboynb/autojson/actions/workflows/android.yml) every five minutes.

IMHO it would be more elegant to use a [scheduled workflow](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) and accept that it's not triggered exactly every five minutes.

I added a test branch for this:

https://github.com/franzs/autojson/commits/test_schedule_cron/

Even with the delay the workflow is run quite regularly:

https://github.com/franzs/autojson/actions

After looking at the file list for the application I think it would be sufficient to run the github action once every hour:

https://sourceforge.net/projects/xiaomi-eu-multilang-miui-roms/files/xiaomi.eu/Xiaomi.eu-app/

**Comment by daboynb** [comment]
I know that is possible, in the previous versions I used cron, but I like to have it every 5 min.

Imagine if the user is in the supermarket and needs to pay :) 

If I trigger it, there will be less chances to have the google wallet not working :)

**Comment by franzs** [comment]
Happy New Year! :tada: 

Ok I see. My preference would be different but I get your point. So lets close this issue.
