### ISSUE TITLE
Not currently working

### ISSUE THREAD

**Issue by brian6932** [daboynb/autojson#4]

**Comment by nyakze** [comment]
Very informative

**Comment by brian6932** [comment]
I'm on 15.4 of https://github.com/chiteroman/PlayIntegrityFix and tried the forks, but it doesn't work, Idk what you want me to say, I'm getting `MEETS_BASIC_INTEGRITY`

**Comment by nyakze** [comment]
Probably related: https://github.com/chiteroman/PlayIntegrityFix/issues/236

**Comment by brian6932** [comment]
Nah not related, I'm not on Android 14 or use a Pixel device

**Comment by nyakze** [comment]
It affects many custom kernels, not just pixel/sultan

**Comment by brian6932** [comment]
I don't use a custom kernel

**Comment by nyakze** [comment]
Then please kindly provide more info on your setup, it's hard to play a guessing game

**Comment by brian6932** [comment]
```
❯ adb shell uname -r
5.10.81-android12-9-dirty
```

**Comment by nyakze** [comment]
Well, there's no problem with the fingerprint as it works on 5 of my devices I've just tested. Google doesn't like something in your setup.

**Comment by brian6932** [comment]
I've been using the same setup for months, and haven't changed a thing, with the exception of updating Play Integrity, and setting this as pif 🤷 been working for a bit, then just stopped

**Comment by nyakze** [comment]
Google changes stuff, not you.

**Comment by brian6932** [comment]
I'm more or less having the same issue as https://github.com/chiteroman/PlayIntegrityFix/issues/231
No matter what version I use, I exhibit it

**Comment by mariuszste** [comment]
`pif_kernel.json`  + chiteroman PIF v15.4 worked for me

Pixel 7 pro, A14, kirisakura kernel
